package com.qz.lifehelper.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

/**
 * Entity mapped to table IMAGE.
 */
public class Image {

    private Long id;
    private java.util.Date createdAt;
    private String imageSrc;

    public Image() {
    }

    public Image(Long id) {
        this.id = id;
    }

    public Image(Long id, java.util.Date createdAt, String imageSrc) {
        this.id = id;
        this.createdAt = createdAt;
        this.imageSrc = imageSrc;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public java.util.Date getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(java.util.Date createdAt) {
        this.createdAt = createdAt;
    }

    public String getImageSrc() {
        return imageSrc;
    }

    public void setImageSrc(String imageSrc) {
        this.imageSrc = imageSrc;
    }

}
